alter session set "_ORACLE_SCRIPT"=true; --Se da problemi di creazione dell'account


--ASSISTENZA: PW: ASSISTENZA
GRANT CREATE SESSION TO ASSISTENZA;
GRANT ALL ON GRUPPO_ASSISTENZA TO ASSISTENZA;
GRANT ALL ON DATA_ASSISTENZA TO ASSISTENZA;
GRANT ALL ON RICHIESTA_DI_SUPPORTO TO ASSISTENZA;
GRANT ALL ON RDS_VEND TO ASSISTENZA;
GRANT ALL ON RDS_ART TO ASSISTENZA;
GRANT ALL ON RIMBORSO TO ASSISTENZA;


--CLIENTE:	PW: CLIENTE
GRANT CREATE SESSION TO CLIENTE;
GRANT SELECT,UPDATE ON ACCOUNT TO CLIENTE;
GRANT SELECT,UPDATE ON CLIENTE TO CLIENTE;
GRANT ALL ON MODALITA_PAGAMENTO TO CLIENTE;
GRANT ALL ON WISHLIST TO CLIENTE;
GRANT ALL ON RECENSIONE TO CLIENTE;
GRANT ALL ON ORDINE TO CLIENTE;
GRANT SELECT ON LICENZA_ARTICOLO TO CLIENTE;
GRANT SELECT ON PRODOTTO_SOFTWARE TO CLIENTE;
GRANT SELECT ON AZIENDA_PROPRIETARIA TO CLIENTE;
GRANT SELECT ON CATEGORIA_SOFTWARE TO CLIENTE;
GRANT SELECT ON HA TO CLIENTE;
GRANT ALL ON CONTIENE TO CLIENTE;
GRANT SELECT ON COMPATIBILITA_SO TO CLIENTE;
GRANT SELECT ON INSERITO TO CLIENTE;
GRANT SELECT ON CATALOGO TO CLIENTE;
GRANT SELECT ON CONTATTI_ASSISTENZA TO CLIENTE;
GRANT SELECT ON CONTATTI_PUBBLICITARI TO CLIENTE;
GRANT SELECT ON PUBBLICITA TO CLIENTE;
GRANT SELECT ON POSSIEDE TO CLIENTE;
GRANT SELECT,INSERT ON RDS_ART TO CLIENTE;
GRANT SELECT ON CLASSIFICA_Categoria_Software TO CLIENTE;
GRANT SELECT ON CLASSIFICA_Prodotto_software TO CLIENTE;
GRANT SELECT ON Visualizza_TOP_venditori TO CLIENTE;
GRANT SELECT ON Visualizza_prodotti_Aziende_prop TO CLIENTE;

--VENDITORE:
GRANT CREATE SESSION TO VENDITORE;
GRANT SELECT ON OFFERTA TO VENDITORE;
GRANT SELECT ON HA TO VENDITORE;
GRANT SELECT,INSERT,UPDATE ON LICENZA_ARTICOLO TO VENDITORE;
GRANT SELECT,UPDATE ON ACCOUNT TO VENDITORE;
GRANT SELECT,UPDATE ON VENDITORE TO VENDITORE;
GRANT SELECT ON PRODOTTO_SOFTWARE TO VENDITORE;
GRANT SELECT ON CATALOGO TO VENDITORE;
GRANT SELECT ON RECENSIONE TO VENDITORE;
GRANT SELECT ON CATEGORIA_SOFTWARE TO VENDITORE;
GRANT SELECT,INSERT ON RDS_VEND TO VENDITORE;
GRANT SELECT ON CLASSIFICA_Categoria_Software TO VENDITORE;
GRANT SELECT ON CLASSIFICA_Prodotto_software TO VENDITORE;
GRANT SELECT ON Visualizza_TOP_venditori TO VENDITORE;
GRANT SELECT ON Visualizza_prodotti_Aziende_prop TO VENDITORE;
grant select on AZIENDA_PROPRIETARIA TO VENDITORE;
grant select on COMPATIBILITA_SO TO VENDITORE;
grant select on INSERITO TO VENDITORE;
grant select on contatti_assistenza TO VENDITORE;
grant select on contatti_pubblicitari TO VENDITORE;
grant select on possiede TO VENDITORE;
grant select on pubblicita TO VENDITORE;




--GESTIONE DELLE PROCEDURE E DELLE VISTE PER OGNI UTENTE:
GRANT EXECUTE ON  PROCEDURE_CREA_Carrello to CLIENTE;
GRANT EXECUTE ON  PROCEDURE_AGGIUNGI_Articolo to CLIENTE;
GRANT EXECUTE ON  PROCEDURE_CHIUDI_Carrello to CLIENTE;
GRANT EXECUTE ON  PROCEDURE_RIMUOVI_Carrello to CLIENTE;
GRANT EXECUTE ON  PROCEDURE_RIMUOVI_Articolo to CLIENTE;
GRANT EXECUTE ON  PROCEDURE_Gestione_Richieste to ASSISTENZA;

GRANT SELECT ON  Licenze_scontate to CLIENTE;
GRANT SELECT ON  CLASSIFICA_Categoria_Software to CLIENTE;
GRANT SELECT ON  CLASSIFICA_Prodotto_software to CLIENTE;
GRANT SELECT ON  Visualizza_Licenze_disponibili to CLIENTE;
GRANT SELECT ON  Visualizza_TOP_venditori to CLIENTE;
GRANT SELECT ON  Visualizza_prodotti_Aziende_prop to CLIENTE;
GRANT SELECT ON  CLASSIFICA_Categoria_Software to VENDITORE;
GRANT SELECT ON  CLASSIFICA_Prodotto_software to VENDITORE;
GRANT SELECT ON  Visualizza_Licenze_disponibili to VENDITORE;
GRANT SELECT ON  Visualizza_TOP_venditori to VENDITORE;
GRANT SELECT ON  Visualizza_prodotti_Aziende_prop to VENDITORE;

--La gestione delle offerte è una procedura che solo l'amministratore può eseguire.












